# Introducción

En este cuaderno estaremos extendiendo la funcionalidad de extracción de las coordenadas GPS y el nombre de un fichero que contiene numerosos talleres con el objetivo de geolocalizarlos en un mapa.

Para ello primero importaremos e instalaremos las librerías y dependencias necesarias

In [2]:
import csv
import pandas as pd
import numpy as np
from geopy.geocoders import ArcGIS
import folium
from scipy.spatial import cKDTree
import networkx as nx
import osmnx as ox
import matplotlib.pyplot as plt

Primeramente cargamos los datos del fichero csv que hemos arrastrado a la carpeta de trabajo

In [3]:
datos = []

csvfile = open("garage_locations.csv", encoding="utf8")
reader = csv.reader(csvfile)

for row in reader:
    datos.append(row)

datos

[['"var optionsMarqueur1 = {position: new google.maps.LatLng(43.6163939,1.4402323),icon: image,map: map};var marqueur1 = new google.maps.Marker(optionsMarqueur1);markers.push(marqueur1);markers_garage.push(marqueur1);var infoBulle1 = new google.maps.InfoWindow({content: contenuInfobulle1});google.maps.event.addListener(marqueur1, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle1.open(map, marqueur1);infoopened = infoBulle1;});google.maps.event.addListener(marqueur1, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle1.open(map, marqueur1);infoopened = infoBulle1;});var image = ""images/carre_rouge.png"";var contenuInfobulle2 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_rouge.png"" alt=""Marqueur Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Carrosserie M. SERVICES AUTOMOBILES\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'31140 AUCAMVILLE\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://carrosseriem_servicesautomobiles."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur2 = {position: new google.maps.LatLng(43.6778143,1.4156883),icon: image,map: map};var marqueur2 = new google.maps.Marker(optionsMarqueur2);markers.push(marqueur2);markers_carrosserie.push(marqueur2);var infoBulle2 = new google.maps.InfoWindow({content: contenuInfobulle2});google.maps.event.addListener(marqueur2, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle2.open(map, marqueur2);infoopened = infoBulle2;});google.maps.event.addListener(marqueur2, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle2.open(map, marqueur2);infoopened = infoBulle2;});var image = ""images/carre_rouge.png"";var contenuInfobulle3 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_rouge.png"" alt=""Marqueur Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage et Carrosserie DELAMAIRE\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'22130 CREHEN\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garageetcarrosseriedelamaire."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur3 = {position: new google.maps.LatLng(48.5428498,-2.2062701),icon: image,map: map};var marqueur3 = new google.maps.Marker(optionsMarqueur3);markers.push(marqueur3);markers_carrosserie.push(marqueur3);var infoBulle3 = new google.maps.InfoWindow({content: contenuInfobulle3});google.maps.event.addListener(marqueur3, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle3.open(map, marqueur3);infoopened = infoBulle3;});google.maps.event.addListener(marqueur3, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle3.open(map, marqueur3);infoopened = infoBulle3;});var image = ""images/carre_rouge.png"";var contenuInfobulle4 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_rouge.png"" alt=""Marqueur Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage MECA SPORT AUTO\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'06370 MOUANS SARTOUX\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garagemecasportauto."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur4 = {position: new google.maps.LatLng(43.6203689,6.972497),icon: image,map: map};var marqueur4 = new google.maps.Marker(optionsMarqueur4);markers.push(marqueur4);markers_carrosserie.push(marqueur4);var infoBulle4 = new google.maps.InfoWindow({content: contenuInfobulle4});google.maps.event.addListener(marqueur4, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle4.open(map, marqueur4);infoopened = infoBulle4;});google.maps.event.addListener(marqueur4, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle4.open(map, marqueur4);infoopened = infoBulle4;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle5 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage et Carrosserie AUTO AGM\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'06250 MOUGINS\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garageetcarrosserieautoagm."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur5 = {position: new google.maps.LatLng(43.6054951,6.9926871),icon: image,map: map};var marqueur5 = new google.maps.Marker(optionsMarqueur5);markers.push(marqueur5);markers_garage_carrosserie.push(marqueur5);var infoBulle5 = new google.maps.InfoWindow({content: contenuInfobulle5});google.maps.event.addListener(marqueur5, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle5.open(map, marqueur5);infoopened = infoBulle5;});google.maps.event.addListener(marqueur5, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle5.open(map, marqueur5);infoopened = infoBulle5;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle6 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Carrosserie M. SERVICES AUTOMOBILES\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'31140 AUCAMVILLE\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://carrosseriem_servicesautomobiles."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur6 = {position: new google.maps.LatLng(43.6778143,1.4156883),icon: image,map: map};var marqueur6 = new google.maps.Marker(optionsMarqueur6);markers.push(marqueur6);markers_garage_carrosserie.push(marqueur6);var infoBulle6 = new google.maps.InfoWindow({content: contenuInfobulle6});google.maps.event.addListener(marqueur6, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle6.open(map, marqueur6);infoopened = infoBulle6;});google.maps.event.addListener(marqueur6, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle6.open(map, marqueur6);infoopened = infoBulle6;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle7 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage SILVESTRE ET FILS\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'05103 BRIANCON CEDEX\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garagesilvestreetfils."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur7 = {position: new google.maps.LatLng(44.884817,6.628008899999941),icon: image,map: map};var marqueur7 = new google.maps.Marker(optionsMarqueur7);markers.push(marqueur7);markers_garage_carrosserie.push(marqueur7);var infoBulle7 = new google.maps.InfoWindow({content: contenuInfobulle7});google.maps.event.addListener(marqueur7, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle7.open(map, marqueur7);infoopened = infoBulle7;});google.maps.event.addListener(marqueur7, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle7.open(map, marqueur7);infoopened = infoBulle7;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle8 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage et Carrosserie COMBE SARL MISTRAL ENTREPRISES\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'13910 MAILLANE\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garageetcarrosseriecombesarlmistralentreprises."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur8 = {position: new google.maps.LatLng(43.8115912,4.8340044),icon: image,map: map};var marqueur8 = new google.maps.Marker(optionsMarqueur8);markers.push(marqueur8);markers_garage_carrosserie.push(marqueur8);var infoBulle8 = new google.maps.InfoWindow({content: contenuInfobulle8});google.maps.event.addListener(marqueur8, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle8.open(map, marqueur8);infoopened = infoBulle8;});google.maps.event.addListener(marqueur8, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle8.open(map, marqueur8);infoopened = infoBulle8;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle9 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage MECA SPORT AUTO\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'06110 LE CANNET\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garagemecasportauto."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur9 = {position: new google.maps.LatLng(43.576551,7.01902),icon: image,map: map};var marqueur9 = new google.maps.Marker(optionsMarqueur9);markers.push(marqueur9);markers_garage_carrosserie.push(marqueur9);var infoBulle9 = new google.maps.InfoWindow({content: contenuInfobulle9});google.maps.event.addListener(marqueur9, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle9.open(map, marqueur9);infoopened = infoBulle9;});google.maps.event.addListener(marqueur9, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle9.open(map, marqueur9);infoopened = infoBulle9;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle11 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Carrosserie THIMONNIER Benoit\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'17450 ST LAURENT DE LA PREE\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://carrosseriethimonnierbenoit."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur11 = {position: new google.maps.LatLng(45.981425,-1.041028),icon: image,map: map};var marqueur11 = new google.maps.Marker(optionsMarqueur11);markers.push(marqueur11);markers_garage_carrosserie.push(marqueur11);var infoBulle11 = new google.maps.InfoWindow({content: contenuInfobulle11});google.maps.event.addListener(marqueur11, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle11.open(map, marqueur11);infoopened = infoBulle11;});google.maps.event.addListener(marqueur11, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle11.open(map, marqueur11);infoopened = infoBulle11;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle12 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Carrosserie SARL MAURIN\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'16100 COGNAC\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://carrosseriesarlmaurin."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur12 = {position: new google.maps.LatLng(45.7059243,-0.3387318),icon: image,map: map};var marqueur12 = new google.maps.Marker(optionsMarqueur12);markers.push(marqueur12);markers_garage_carrosserie.push(marqueur12);var infoBulle12 = new google.maps.InfoWindow({content: contenuInfobulle12});google.maps.event.addListener(marqueur12, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle12.open(map, marqueur12);infoopened = infoBulle12;});google.maps.event.addListener(marqueur12, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle12.open(map, marqueur12);infoopened = infoBulle12;});var image = ""images/carre_bleu_rouge.png"";var contenuInfobulle13 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu_rouge.png"" alt=""Marqueur Garage - Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Garage et Carrosserie OLIVIER\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'38570 LE CHEYLAS\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garageetcarrosserieolivier."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur13 = {position: new google.maps.LatLng(45.370801,5.992381),icon: image,map: map};var marqueur13 = new google.maps.Marker(optionsMarqueur13);markers.push(marqueur13);markers_garage_carrosserie.push(marqueur13);var infoBulle13 = new google.maps.InfoWindow({content: contenuInfobulle13});google.maps.event.addListener(marqueur13, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle13.open(map, marqueur13);infoopened = infoBulle13;});google.maps.event.addListener(marqueur13, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle13.open(map, marqueur13);infoopened = infoBulle13;});var image = ""images/carre_rouge.png"";var contenuInfobulle14 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_rouge.png"" alt=""Marqueur Carrosserie""/>\' + \'<h1 class=""left"">\' + \'Carrosserie PELAGE BRUNO\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'33300 BORDEAUX\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://carrosseriepelagebruno."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur14 = {position: new google.maps.LatLng(44.8631352,-0.5604802),icon: image,map: map};var marqueur14 = new google.maps.Marker(optionsMarqueur14);markers.push(marqueur14);markers_carrosserie.push(marqueur14);var infoBulle14 = new google.maps.InfoWindow({content: contenuInfobulle14});google.maps.event.addListener(marqueur14, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle14.open(map, marqueur14);infoopened = infoBulle14;});google.maps.event.addListener(marqueur14, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle14.open(map, marqueur14);infoopened = infoBulle14;});var image = ""images/carre_bleu.png"";var contenuInfobulle16 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu.png"" alt=""Marqueur Garage""/>\' + \'<h1 class=""left"">\' + \'Garage SAINT-JUSTIN\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'40240 SAINT-JUSTIN\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garagesaintjustin."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],
 ['"var optionsMarqueur16 = {position: new google.maps.LatLng(43.981557,-0.229919),icon: image,map: map};var marqueur16 = new google.maps.Marker(optionsMarqueur16);markers.push(marqueur16);markers_garage.push(marqueur16);var infoBulle16 = new google.maps.InfoWindow({content: contenuInfobulle16});google.maps.event.addListener(marqueur16, ""mouseover"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle16.open(map, marqueur16);infoopened = infoBulle16;});google.maps.event.addListener(marqueur16, ""click"", function() {if (typeof( window.infoopened ) != ""undefined"") { infoopened.close(); }infoBulle16.open(map, marqueur16);infoopened = infoBulle16;});var image = ""images/carre_bleu.png"";var contenuInfobulle17 =  \'<div class=""map_popup"">\' + \'<div class=""left map_popup_txt"">\' + \'<div class=""wrapper_contenu_infobulle"">\' + \'<img class=""left"" src=""images/carre_bleu.png"" alt=""Marqueur Garage""/>\' + \'<h1 class=""left"">\' + \'Garage GARCIA HERMANOS\' + \'</h1>\' + \'<div class=""clear""> </div>\' + \'<p>\' + \'40370 RION DES LANDES\' + \'</p>\' + \'</div>\' + \'<div class=""wrapper_lien_web"">\' + \'<hr/>\' + \'<a target=""_blank"" class=""lien_web redirect_presentation"" href=""http://garagegarciahermanos."">\' + \'Site web\' + \'</a>\' + \'</div>\' + \'<div class=""clear""> </div>\' + \'</div>\' + \'</div>\';"'],

Ahora procederemos a extraer la información del nombre del taller y sus coordenadas GPS de cada uno de los registros del fichero

In [4]:
listacompleta = []

for x in range(0, len(datos)):

  cadena = str(datos[x])

  subcadena1 = r"LatLng("
  subcadena2 = r"),icon:"
  subcadena3 = r"<h1 class="
  subcadena4 = r"\' + \'</h1>\' + \'"

  ilatlong = cadena.find(subcadena1)+7
  flatlong = cadena.find(subcadena2)
  cadena_1 = cadena[ilatlong:flatlong]
  latlong = cadena_1.split(sep=",")

  inombre = cadena.find(subcadena3)+26
  fnombre = cadena.find(subcadena4)
  nombre = cadena[inombre:fnombre]

  fila = [nombre, (latlong[0]), (latlong[1])]

  listacompleta.append(fila)

listacompleta

[['Carrosserie M. SERVICES AUTOMOBILES', '43.6163939', '1.4402323'],
 ['Garage et Carrosserie DELAMAIRE', '43.6778143', '1.4156883'],
 ['Garage MECA SPORT AUTO', '48.5428498', '-2.2062701'],
 ['Garage et Carrosserie AUTO AGM', '43.6203689', '6.972497'],
 ['Carrosserie M. SERVICES AUTOMOBILES', '43.6054951', '6.9926871'],
 ['Garage SILVESTRE ET FILS', '43.6778143', '1.4156883'],
 ['Garage et Carrosserie COMBE SARL MISTRAL ENTREPRISES',
  '44.884817',
  '6.628008899999941'],
 ['Garage MECA SPORT AUTO', '43.8115912', '4.8340044'],
 ['Carrosserie THIMONNIER Benoit', '43.576551', '7.01902'],
 ['Carrosserie SARL MAURIN', '45.981425', '-1.041028'],
 ['Garage et Carrosserie OLIVIER', '45.7059243', '-0.3387318'],
 ['Carrosserie PELAGE BRUNO', '45.370801', '5.992381'],
 ['Garage SAINT-JUSTIN', '44.8631352', '-0.5604802'],
 ['Garage GARCIA HERMANOS', '43.981557', '-0.229919'],
 ['Garage CARROSSERIE DU MIDI', '43.933607', '-0.920563'],
 ['Garage CAZOULS AUTO DISTRIBUTION', '43.5572492', '3.7968754'],
 ['Carrosserie GROSSO Jérome', '43.385791', '3.1142765'],
 ['Garage MAROSSERO &amp; FILS', '43.488777', '3.669152'],
 ['Garage PUGET', '43.2418842', '5.3981698'],
 ['Garage DE LA COMTESSE', '43.2896879', '5.3730693'],
 ['Garage GAVOTTE AUTO', '43.3134272', '5.4473535'],
 ['Garage AUTOREP', '43.3910556', '5.341666'],
 ['Garage CALENDINI &amp; BRUNETON', '43.3056316', '5.3822803'],
 ['Garage ERRICO', '43.26787', '5.4148238'],
 ['Garage A.C.M.A', '43.29107090000001', '5.4228462999999465'],
 ['Garage SF AUTOMOBILES', '43.390916', '5.233463'],
 ['Garage AUTOS DU ROVE', '43.422206', '5.2316903'],
 ['Garage SM AUTOMOBILES', '43.3685529', '5.2449676'],
 ['Carrosserie SANDRE SA', '47.4246052', '-0.557982'],
 ['Carrosserie BS AUTO SPORT', '43.355598', '1.4673147'],
 ['Carrosserie BACCARINI JEAN FRANCOIS', '43.51563', '1.499573'],
 ['Carrosserie DAVID BLANC', '43.6138369', '1.081741'],
 ['Carrosserie BARY CARROSSERIE', '44.292917', '2.559434'],
 ['Carrosserie Patrick BERTRAND', '43.2071865', '2.3801284'],
 ['Garage Carrosserie Daniel SUCHON', '43.529232', '1.760954'],
 ['Garage S.A.S.U GUIBERT', '44.53123', '4.6888239'],
 ['Garage ARMORIQUE SARL', '44.1095259', '5.1044844'],
 ['Garage de la Croix', '48.4205364', '-2.4411909'],
 ['Garage DANET', '48.397172', '-2.733427'],
 ['Garage LBR AUTO', '48.557172', '-2.532964'],
 ['Garage DB AUTO', '48.5193724', '-2.7878711'],
 ['Garage AUTO MINUTE PAIMPOL', '48.7187613', '-3.4148373'],
 ['Garage de BRUSVILY', '48.769687', '-3.067366'],
 ['Garage SEBASTIEN HUE', '48.3903553', '-2.1292534'],
 ["Garage de L\\\\\\'Enseigne", '48.5583602', '-2.3796298'],
 ['Garage Carrosserie CJ AUTO MECA', '48.3622738', '-2.6195154'],
 ['Garage Carrosserie HADOL AUTOMOBILES GURY JEAN CLAUDE',
  '48.1953747',
  '6.4405062'],
 ['Garage BARBESANT', '48.091263', '6.478316'],
 ['Garage Carrosserie MC AUTO 88', '48.0963565', '6.606799'],
 ['Carrosserie JP CARROSSERIE', '48.1968394', '6.3619995'],
 ['Garage GELLEE BENOIT', '48.0602789', '6.6807508'],
 ['Garage des Fontaines', '49.729036', '1.868043'],
 ['Garage AUTO COMPTOIR PROVINOIS', '49.775453', '1.98463'],
 ['Garage KERIVEL Sylvain', '48.5578878', '3.3029197'],
 ["Garage L\\\\\\'hiver Patrice", '48.9170299', '-1.435265'],
 ['Garage Dominique Virginie', '49.5174444', '-1.8116659'],
 ['Garage LESAUVAGE Raphaël', '49.2894476', '-1.5457048'],
 ['Garage HERVIEU', '48.8491921', '-1.2073005'],
 ['Carrosserie DESLANDES', '49.025993', '-1.2844009'],
 ['Carrosserie DESPREZ Jean-Noel', '49.061203', '-1.4346874'],
 ['Garage MAUDUIT', '48.8006953', '-1.3969225'],
 ['Garage Carrosserie VARIN DOMINIQUE', '49.0717291', '-1.5382741'],
 ['Carrosserie SARL DAVID YONNET', '49.5195724', '-1.683697'],
 ['Garage Carrosserie SARL GARAGE SAINT-GILLES', '49.0205976', '-1.4545332'],
 ['Garage AUTOMOBILES DESPREZ', '49.1028241', '-1.1571409'],
 ["Garage du VAL D\\\\\\'OUVE", '48.6988602', '-1.343812'],
 ["Carrosserie Garage de l\\\\\\'Europe", '49.3718449', '-1.5325996'],
 ['Garage SAPET', '48.8541916', '2.4476942'],
 ['Garage SARZIER SARL', '45.086423', '4.627967'],
 ['Garage CHAMPGRAND', '45.0674113', '4.8012987'],
 ['Garage TRUCHET', '44.750336', '4.7871'],
 ['Garage Carrosserie TRITZ Gilbert', '44.944816', '4.841903'],
 ['Garage Carrosserie AS PERFO', '48.8639606', '7.1956666'],
 ['Garage DU CENTRE ERCKER A', '48.816305', '7.007135'],
 ['Garage STEPHANE HENRY', '48.940581', '7.089694'],
 ['Garage ARIANE AUTOS', '48.5761291', '6.9461826'],
 ['Garage SEBASTIEN GUIRAUD', '48.725246', '7.084579'],
 ['Garage SAURET', '43.265801', '2.9453326'],
 ['Garage SARL GARAGE DU CEP', '42.995799', '2.81373'],
 ['Garage VAZ', '43.051963', '2.6625009'],
 ['Garage MP AUTO', '43.021342', '3.043916'],
 ['Garage BELLE ISLE AUTO', '43.1816595', '2.987898'],
 ['Garage TECHNIC AUTO', '43.200503', '2.7577759'],
 ['Garage AMR AUTO', '43.1729151', '2.9839069'],
 ['Garage GANIAGE HERVE', '49.4295387', '2.0807123'],
 ['Garage Carrosserie DUVAL Père et Fils', '49.3826038', '2.2346111'],
 ['Garage AUTO PIECES SERVICES', '49.6091862', '2.0752589'],
 ['Garage STOCK ROUTE', '49.505432', '2.435059'],
 ['Garage RAULT MECANIQUE', '49.234163', '2.305863000000045'],
 ['Garage de SAVIGNIES', '49.329992', '2.440265'],
 ['Garage DELAFONTAINE', '49.464364', '1.9660219'],
 ['Garage DE LA HAUTE SOMME', '49.407953', '2.007353'],
 ['Garage du Rond Point', '49.9029385', '2.5072585'],
 ['Garage LASAGA', '43.482518', '-1.14536'],
 ['Carrosserie FIDALGO', '43.345252', '-1.195965'],
 ['Garage NINAUTO', '43.4863742', '-1.5360276'],
 ['Garage Carrosserie ARRIETA T &amp; S', '43.2302466', '-0.8737607'],
 ['Garage ADRIEN AUTOMOBILES', '43.4056708', '-1.4681892'],
 ['Garage LAKA', '43.492949', '-1.474841'],
 ['Garage J.D AUTO', '43.257002', '-1.2334620000000314'],
 ['Garage MARINELA AUTOMOBILES', '43.362402', '-1.700075'],
 ['Garage FRERET CHRISTIAN SARL', '43.3809828', '-1.6662447'],
 ['Garage GELLE', '46.580224', '0.340375'],
 ['Garage SARL OIRON GARAGE', '47.0312119', '-0.493001'],
 ['Garage GRIGNON JOEL', '46.951073', '-0.080291'],
 ['Garage BERNARDEAU Ph.', '46.9463121', '0.4161506'],
 ['Garage BDM - DUVALS', '46.6844937', '0.2547672'],
 ['Garage J.M BERLAUD', '46.727863', '-0.166042'],
 ['Garage MECAUTO', '46.8160678', '0.5373869'],
 ['Carrosserie Lussacoise', '46.6142898', '0.4147243'],
 ['Garage SARL PICOSSON', '46.3986408', '0.7309237'],
 ['Garage VANDERHOVEN', '46.478495', '0.519944'],
 ['Garage EURL JARRY Alain', '46.753828', '0.486032'],
 ['Carrosserie MECANIQUE', '46.1539119', '0.296578'],
 ['Garage DEGUIL P.', '46.6462674', '0.1713992'],
 ['Garage LE BOURESSOIS', '46.836882', '0.091108'],
 ['Garage DIX &amp; AUTO', '46.3641665', '0.6065982'],
 ['Garage MJ AUTOMOBILES', '46.700301', '0.430684'],
 ['Garage Yoann GUIHARD', '46.667579', '-0.2299657'],
 ['Garage BERRIC SERVICES AUTO', '47.537601', '-2.39816'],
 ['Garage CADEN AUTO SERVICES', '47.632677', '-2.525198'],
 ['Garage DU LOCH', '47.6361588', '-2.2907165'],
 ['Carrosserie Auto Sport Collection', '47.758377', '-2.776469'],
 ['Garage TY GARAGE', '47.619668', '-2.918284'],
 ['Garage du LANDY', '47.619668', '-2.918284'],
 ['Garage DELCLAUX FRERES', '47.62936', '-2.649744'],
 ['Garage PLOUHINEC AUTOMOBILES', '47.6794952', '-2.7354629'],
 ['Garage TASTARD SEBASTIEN', '47.6959932', '-3.2471948'],
 ['Garage ATS', '47.7337634', '-2.5878691'],
 ['Garage de la Cantine', '46.373565', '6.477635'],
 ['Garage du C.E.S', '43.6382323', '6.864584'],
 ['Garage ALAIN GARAGE', '43.5524738', '6.9665476'],
 ['Garage de la BEGUDE', '43.6245929', '6.9274025'],
 ['Garage BOUTAIRE', '43.680845', '6.586749'],
 ['Garage LAND TECHNIC SERVICES', '43.600762', '6.912258'],
 ['Garage FC GARAGE', '43.5755392', '6.9925838'],
 ['Garage LA CARROSSERIE', '43.602967', '6.765181'],
 ['Garage POLLART', '43.698521', '6.847956'],
 ['Garage et Carrosserie BS AUTOMOBILES', '43.6448151', '6.8931074'],
 ['Garage STATION JOFFRE', '43.5928056', '7.0012085'],
 ['Garage S.A.M.D MISTRAL', '43.6976904', '7.259676'],
 ['Garage INTER-CHOC', '43.726647', '7.0947123'],
 ['Garage Lechaux Sarl', '43.6555202', '7.1522014'],
 ['Garage DU GOLF', '48.117947', '-1.6592981'],
 ['Garage BREAL AUTOMOBILES', '48.0790586', '-1.7394564'],
 ['Garage de Ker Anna', '48.0660349', '-1.860572300000058'],
 ['Garage Guillaume ROBIN', '47.6895477', '-2.1393993'],
 ['Garage JANS AUTOMOBILES', '47.574325', '-2.1236419'],
 ['Garage Carrosserie GUILLERM Roger et Charles', '47.6184649', '-1.6158058'],
 ['Garage SARL LARBIOU', '47.680086', '-2.060333'],
 ['Garage ETS DARDAR', '48.216365', '-1.697343'],
 ['Carrosserie BEAUDOUIN', '48.042693', '-1.6618139'],
 ['Garage DE JOVAL', '48.1855757', '-1.6318093'],
 ['Garage Guillaume LAURENT', '48.1336749', '-1.533848'],
 ['Garage LEGLISE GUILLAUME', '48.1173421', '-1.7075198'],
 ['Garage BPM', '47.7205299', '-1.848398'],
 ['Garage BEAUVOIS', '48.3638366', '-1.5669599'],
 ['Garage WAELES Philippe', '50.8195861', '2.3018233'],
 ['Garage PHILAUTOSERVICES', '50.816405', '2.575222'],
 ['Garage RONCQ AUTOMOBILES', '50.7415576', '3.1669265'],
 ["Garage EQUIP\\\\\\'AUTO", '50.7503904', '3.1200083'],
 ['Garage Carrosserie HAVET', '50.8551251', '2.2034148000000187'],
 ['Garage de la Mairie', '50.6576949', '2.694606'],
 ['Garage EXPRESS AUTO', '50.9232193', '1.8885904'],
 ['Garage D.F. AUTO SERVICES', '50.7017417', '3.1719079'],
 ['Garage MECA SERVICES 62', '50.4233037', '2.7629313'],
 ['Garage HANDI AUTO SERVICE', '50.4876636', '2.8560757'],
 ['Garage Carrosserie DAVID DURAN', '50.4048879', '2.8710419999999885'],
 ['Garage TURCK PHILIPPE', '50.3821803', '3.5507672'],
 ['Garage LAUDSPORT RACING SERVICES', '50.7201976', '2.8036732'],
 ['Carrosserie ESSALMI', '50.7917488', '2.6425526'],
 ['Garage MULTISERVICES EXPRESS', '50.6927049', '3.177847'],
 ['Garage PRO-VIN', '50.7141057', '3.1617456'],
 ['Garage MARC DUMON', '50.5117466', '2.9116222'],
 ['Garage ANNOT PNEUS OTTA', '44.2134405', '5.9218613'],
 ['Garage MECA ASPRES', '43.966368', '6.666861'],
 ["Garage LAMOL\\\\\\'S AUTO", '44.523133', '5.749486'],
 ['Garage du Plan', '44.3863', '6.650463'],
 ['Garage CHERFILS PATRICK', '43.9595709', '6.781509'],
 ['Garage PBM', '43.910292', '5.715193999999997'],
 ['Garage PROVENCE SERVICES', '44.342707', '6.028186'],
 ['Garage JMC-AUTO', '43.914706', '5.921487'],
 ['Garage 180 RS', '44.028941', '5.975404'],
 ['Garage SNEGP AUTO', '43.951368', '5.857646'],
 ['Garage CDR', '44.09457', '6.002848'],
 ['Garage PALAVAS AUTO', '43.610769', '3.876716'],
 ['Garage MARTINEZ et Fils', '43.5312791', '3.9395978'],
 ['Garage VASSALO', '43.5968596', '3.8502617'],
 ['Garage SUD VO', '43.6061449', '3.8865359'],
 ['Garage AUTOMOBILE CANETOIS', '43.6371584', '3.9304289'],
 ['Garage du VERSANT MELLINAS ANTOINE', '43.6042289', '3.4790949'],
 ['Garage PAILLADE AUTO CDR MONTPELLIER NORD', '43.6654073', '4.0375095'],
 ['Garage SAINT MARTIN AUTOMOBILE', '43.6344368', '3.8231447'],
 ['Garage ARENA AUTOMOBILES', '43.813994', '3.694862'],
 ['Garage GANGES AUTOS', '43.5968596', '3.8502617'],
 ['Garage SOLER Daniel', '43.9330025', '3.7036872'],
 ['Garage DAV AUTOMOBILES', '43.728422', '4.348684'],
 ['Garage Carrosserie SARL VIGOUROUX', '43.798693', '4.3533486'],
 ['Garage AUTO ASSISTANCE GARDOISE', '44.261034', '4.648079'],
 ['Garage JUAN - Mas de Cheylon', '43.9335718', '4.2440358'],
 ['Garage Y AUTOS', '43.800283', '4.340548'],
 ['Garage TUDELA CDR GROUP', '43.7954862', '4.4193012'],
 ['Garage ROQUE CDR GROUP', '43.7282522', '4.1904034'],
 ['Garage Carrosserie MECANIQUE CARROSSERIE VENTES', '43.814465', '4.3375769'],
 ['Carrosserie E.PROST', '44.65447', '-0.1982596'],
 ['Carrosserie DTA', '44.176374', '0.2959356'],
 ['Garage SF MECAPRO', '44.4387029', '0.620852'],
 ['Carrosserie Joël MARTIN', '44.306736', '0.85813'],
 ["Garage FALC\\\\\\'AUTO", '44.379587', '-0.258759'],
 ['Garage PASSION AUTO 47', '44.174192', '0.690383'],
 ['Garage RUBELLES AUTO', '44.4041684', '0.6905675'],
 ['Garage SARL des CHAUDINS', '48.5572848', '2.6737434'],
 ['Garage Du CENTRE', '48.2647091', '2.7019963'],
 ['Garage REPARECO', '48.1629182', '2.2587527'],
 ['Garage A.S.J.', '48.565306', '2.613554'],
 ['Carrosserie DES CHALETS', '48.004543', '2.533953'],
 ['Carrosserie FOLGARIENNE', '48.7687174', '2.4137829'],
 ['SARL Garage CARDEILLAC', '43.774743', '-0.180098'],
 ['Garage GIAVARINI GILLES', '43.90185', '0.27274'],
 ['Garage JMT RACING', '43.690489', '0.915081'],
 ['Garage TURQUIN Michel', '43.6199832', '1.1006757'],
 ['Carrosserie Casse Auto Gimontoise', '43.654834', '0.74592'],
 ['Garage LETT SPORT', '43.626348', '0.876768'],
 ['Garage Carrosserie AUTOMOBILES COMA', '43.500014', '0.213362'],
 ['Garage SCC SERVICES', '43.9462245', '0.0874434'],
 ['Garage ARROS PIECES GARAGE', '43.70493889999999', '-0.2594547999999577'],
 ['Garage BACQUIE AUTOMOBILES SAS', '43.6055722', '0.049337400000013076'],
 ['Garage DE LA PLAINE', '43.849456', '0.6632439'],
 ['Garage ANDRIEUX', '43.824232', '-0.147878'],
 ['Garage Carrosserie FRANCK RINGENBACH', '43.9575696', '0.3660443'],
 ['Garage MENDEZ', '43.469712', '0.310348'],
 ['Garage DTM AUTOS', '43.8557984', '0.0914714'],
 ['Garage TEYSSIER AUCH', '43.933604', '0.623621'],
 ['Garage AUCH MOULEDOUS AUTO', '43.64638', '0.586709'],
 ['Garage HINSINGER', '43.6555729', '0.6237602'],
 ['Garage Ets Peyrichou', '43.759272', '0.3015939'],
 ['Garage AUTOMOBILE DU ROND-POINT', '44.8540216', '0.4855962'],
 ['Garage Patrice VERGNEAU', '44.854658', '0.563471'],
 ['Carrosserie JOUBERT', '44.846628', '0.4947554'],
 ['Carrosserie MERCIER', '46.160329', '-1.151139'],
 ['Garage AUTO SOLUTIONS', '45.899687', '-0.950687'],
 ['Carrosserie Automobile CORABOEUF', '47.4996599', '-0.5838417'],
 ['Garage Jean-Luc CIRON', '47.357131', '-1.015158'],
 ['Carrosserie MONTLIMARTOISE', '47.5634865', '-0.6798902'],
 ['Carrosserie Pescheux', '47.269759', '-1.026043'],
 ['Garage ACA Deschamps', '47.4151801', '-0.9156752'],
 ['Garage MARCELLI ROBERT', '47.5135829', '0.1192672'],
 ["Garage MECA\\\\\\'SERVICES", '42.463592', '9.207077900000058'],
 ['Garage BMK AUTO', '42.445813', '9.5078'],
 ['Garage ADRIAN', '43.2845813', '5.5986885'],
 ['Garage DAVESNE &amp; CIE', '49.3967998', '4.6935995'],
 ['Carrosserie MARIE', '49.7689975', '4.7130006'],
 ['Garage PILOTE DS AUTO', '43.9044018', '1.9083807'],
 ['Carrosserie SARL TOURNIER', '43.953034', '2.170646'],
 ['Garage Carrosserie LOPEZ', '43.8254795', '1.7213607'],
 ['Carrosserie MOREL', '44.0556223', '2.1467777'],
 ['Carrosserie Frédéric ROJON', '45.1433613', '5.7081457'],
 ['Carrosserie Pont Eveque Auto', '45.4448461', '5.2924415'],
 ['Carrosserie BOURGOIN CARROSSERIE AUTOMOBILES', '45.530442', '4.912872'],
 ['Garage du Rond Point', '45.5920372', '5.264736'],
 ['Garage Carrosserie PROXI-AUTO', '47.27448', '-1.7798784'],
 ['Garage Clavier Sébastien', '47.261903', '-1.4943084000000226'],
 ['Garage L. THIBAUD/garage Versailles 44', '47.143462', '-1.694164'],
 ['Garage SARL GOUILLANDEAU Didier', '47.2251212', '-1.5553479'],
 ['Garage NG AUTO', '47.187575', '-1.4411473'],
 ['Garage SARL MINGUET', '47.2613516', '-1.6520127999999659'],
 ['Carrosserie LOIRE CARROSSERIE', '47.217791', '-1.6129218'],
 ['Garage MORILLE SARL', '47.330145', '-0.237555'],
 ['Garage EURL MABILLEAU', '47.374699', '-0.688929'],
 ['Garage Carrosserie SARL JALLIER-COURANT', '47.277136', '-0.3606874'],
 ['Garage Carrosserie Joel ROCHARD', '47.092058', '-0.910353'],
 ['Garage VAUBAN', '47.266427', '-0.576541'],
 ['Garage PLANCHENAULT', '47.4585347', '-0.5618534'],
 ['Garage AUGUSTE JOURDAN', '47.3911977', '-0.050903'],
 ['Garage Jérémy BRIAND', '48.4148674', '-1.733042'],
 ['Garage MARUITTE', '48.58523', '-1.83507'],
 ['Garage Carrosserie BENOIT', '47.6055343', '2.0243543'],
 ['Garage Carrosserie MCPS', '48.0011322', '2.094951'],
 ['Garage du Loiret', '47.8444909', '2.0337085'],
 ['Garage ESTORIL AUTOS', '47.8669552', '1.9014116'],
 ['Carrosserie DES SERRES', '49.00538', '2.279543'],
 ['Carrosserie SARL SPECIAL CARROSSERIE', '43.6993113', '7.1972283'],
 ['Carrosserie DE FALICON', '43.63476989999999', '6.957552299999975'],
 ['Carrosserie FLAVIO', '43.7615264', '7.2604606'],
 ['Carrosserie AUTORAMA', '43.5968913', '7.1096358'],
 ['Carrosserie AUTO QUALITE', '43.7255482', '7.2850516'],
 ['Carrosserie PLAN DE GATTIERES', '43.7072982', '7.2903145'],
 ["Carrosserie EUROP\\\\\\'MOTORS", '43.7597268', '7.1900053'],
 ['Garage Carrosserie LOGERIE', '43.7475809', '7.3318231'],
 ['Garage DE LA MER', '47.142525', '-2.2072822'],
 ['Garage LECONTE Bertrand', '49.956032', '1.1873625'],
 ['Garage FERBER J.L', '49.708866', '1.224563'],
 ['Garage 3 A SERVICES', '47.8540485', '7.513952'],
 ['Garage GLOBAL AUTO', '47.5633541', '7.1878115'],
 ['Garage MCP AUTO', '47.768574', '7.302206'],
 ['Garage 2G AUTOMOBILES', '47.6563681', '7.1005491'],
 ['Garage AUTO GARREFFA et FRERES', '47.8027813', '7.1767384'],
 ['Garage Carrosserie MICHEL S.A.S', '47.9065861', '7.2185881'],
 ['Garage UZUN OTOMOTIV', '47.6805529', '7.2152589'],
 ['Garage Carrosserie RC GARAGE', '47.625195', '6.8432665'],
 ["Garage Ets Pour l\\\\\\'Auto Multimarque", '47.5535454', '7.3139591'],
 ['Garage PEREA ET FILS', '43.4112718', '3.7065537'],
 ['Garage SARL ABS34', '43.4083177', '3.6942088'],
 ['Garage THAU CARBURE', '43.4078758', '3.7008219'],
 ['Garage Brece Auto Mécanique', '43.449477', '3.654138'],
 ['Garage Beaulieu', '48.104415', '-1.486342'],
 ['Garage Renoult', '48.177218', '-1.301799'],
 ['Garage DAMON', '48.174944', '-1.188856'],
 ['Garage Frémont (ex Pocé Auto Services)', '48.008012', '-1.289755'],
 ['Garage Louvigné Auto Services', '48.114961', '-1.249732'],
 ['Garage Châtillon Auto Services', '48.0534542', '-1.3202475'],
 ['Garage de La Blinière', '48.224996', '-1.180487'],
 ['Garage Milet S.A.R.L.', '48.0580969', '-1.159842'],
 ['Garage de la Rocade Sud', '48.1086563', '-1.209467'],
 ['Garage Alain PICHOT', '48.0840507', '-1.6967947'],
 ['Garage Goven Auto Services', '48.1839385', '-1.434705'],
 ['Garage Breteil Auto Services', '48.007361', '-1.8450002'],
 ['Garage Vern Auto Services (STATION AVIA)', '48.1447805', '-1.895595'],
 ['Garage CHATEAUGIRON AUTO SERVICES', '48.046029', '-1.602986'],
 ['Garage GALLAIS', '48.0531001', '-1.5088549'],
 ['Garage LEJANVRE', '48.1979007', '-2.0421883'],
 ['Garage ROUGÉ AUTOMOBILES', '48.5333491', '-1.5543976000000157'],
 ['Garage MAURON AUTOMOBILES', '47.783956', '-1.450126'],
 ['Garage AUTO ASSISTANCE', '48.083875', '-2.283582'],
 ['Garage Carrosserie du Vert Galant', '48.6319149', '-1.9815769'],
 ['Garage Auto Services Guerchais', '48.2098819', '-1.5159652'],
 ['Garage GESNOUIN AUTOMOBILES', '47.9427715', '-1.2336323'],
 ['Garage BESS AUTO', '48.346379', '-1.272484'],
 ['Garage DENAIS', '48.079081', '-1.398454'],
 ['Garage AXESS AUTOMOBILES', '48.1122513', '-1.204499'],
 ['Garage LAVAL AUTO 53', '47.246659', '-2.165807'],
 ['Garage AUTO PLUS 53', '48.098688', '-0.788908'],
 ['Garage DIDIER RENIER', '47.997267', '-0.715603'],
 ['Garage de MONTIGNY', '47.8457135', '-0.9119403'],
 ['Garage RV AUTOMOBILES', '48.302381', '-0.6115232'],
 ['Garage Claude GUILLET', '48.069215', '-0.82895'],
 ['Garage BONNET', '47.4734282', '1.6306548999999677'],
 ['Garage XAVIER SIMON', '47.1625607', '1.5543583'],
 ['Garage Christophe HERAULT', '47.589656', '1.657635'],
 ["Garage CENTRAL\\\\\\'AUTO 41", '47.2932333', '1.7660407'],
 ['Garage LE GARREC', '47.717956', '1.604584'],
 ['Garage INIAL BRUNO', '47.4140946', '1.5171372'],
 ['Garage VAL DE LOIRE AUTOS', '47.2574634', '1.6551845'],
 ['Garage ROMO PIECES AUTO', '47.5633234', '1.3701864'],
 ['Garage Philippe MENAGER', '47.399643', '1.746105'],
 ['Garage BALLY AUTOMOBILES', '47.7570448', '0.8633348'],
 ['Garage Carrosserie MOSNIER et Fils', '47.322178', '1.670707'],
 ['Carrosserie DUREAU Jean Christophe', '47.6084359', '1.9092693'],
 ["Garage SARL DAG\\\\\\'AUTOS", '45.108274', '-0.585249'],
 ['Garage Rossignol', '44.9481426', '-0.3513021'],
 ['Garage AUTO BOBY', '45.0419463', '-0.553215899999941'],
 ['Garage DU CENTRE', '45.13955', '-0.542023'],
 ['Garage POTIER SARL DPB', '45.1343729', '-0.397357'],
 ['Garage GRANGER Frédéric', '45.1611136', '-0.6221672'],

Ahora procederemos a guardar el listado de talleres en un DataFrame con tres features:

* Nombre del Taller
* Latitud
* Longitud

In [5]:
df = pd.DataFrame()
df = pd.DataFrame(listacompleta, columns=['Nombre del Taller', 'Latitud', 'Longitud'])
df['Nombre del Taller'] = df['Nombre del Taller'].replace({'\\\\':''}, regex=True)
df

,Nombre del Taller,Latitud,Longitud
0,Carrosserie M. SERVICES AUTOMOBILES,43.6163939,1.4402323
1,Garage et Carrosserie DELAMAIRE,43.6778143,1.4156883
2,Garage MECA SPORT AUTO,48.5428498,-2.2062701
3,Garage et Carrosserie AUTO AGM,43.6203689,6.972497
4,Carrosserie M. SERVICES AUTOMOBILES,43.6054951,6.9926871
...,...,...,...
678,Garage Carrosserie GRANGIER,47.9291299,-1.941751599999975
679,Garage BLANCHET Nicolas,47.425029,2.053595
680,Garage AUTO OCCASION SERVICE,47.82355330000001,1.2957106999999723
681,Carrosserie PRECICAR,48.5076567,-4.0748286
682,UN SALUDO DESDE SANTANDER,43.46235,-3.80997

Procederemos a limpiar el DataFrame de valores perdidos y reseteamos los índices ya que después vamos a iterar sobre el dataframe.

In [6]:
df1 = pd.DataFrame()
df1 = df.dropna()
df1.reset_index(drop=True, inplace=True)

print(df1.info())

<class 'pandas.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nombre del Taller  683 non-null    str
 1   Latitud            683 non-null    str
 2   Longitud           683 non-null    str
dtypes: str(3)
memory usage: 16.1 KB
None

Ahora utilizaremos un geolocalizador para enrriquecer el DataFrame con nuevas features calculadas a partir de las coordenadas GPS.

In [7]:
localización = []

geolocator = ArcGIS(user_agent="Mi_Geolocalizador")

for index, row in df1.iterrows():
  location = geolocator.reverse((row['Latitud'], row['Longitud']), timeout=None)
  localización.append(location.raw)

Antes de añadir las nuevas features al DataFrame comprobamos que la extracción de información haya sido correcta.

In [8]:
print(localización[0])

{'Match_addr': 'Autosur', 'LongLabel': 'Autosur, 51 Boulevard des Minimes, 31200, Toulouse, Haute-Garonne, Occitanie, FRA', 'ShortLabel': 'Autosur', 'Addr_type': 'POI', 'Type': 'Government Office', 'PlaceName': 'Autosur', 'AddNum': '51', 'Address': '51 Boulevard des Minimes', 'Block': '', 'Sector': '', 'Neighborhood': '', 'District': '', 'City': 'Toulouse', 'MetroArea': '', 'Subregion': 'Haute-Garonne', 'Region': 'Occitanie', 'RegionAbbr': 'OCC', 'Territory': '', 'Postal': '31200', 'PostalExt': '', 'CntryName': 'France', 'CountryCode': 'FRA', 'X': 1.44018, 'Y': 43.61625, 'InputX': 1.4402323, 'InputY': 43.6163939, 'StrucType': '', 'StrucDet': ''}

Añadiremos las features seleccionadas al DataFrame. Note que lo estamos haciendo sobre un nuevo DataFrame para dejar una copia intacta del DataFrame original.

In [9]:
Calle = []
Codigo_Postal = []
Ciudad = []
Departamento = []

for i in range(0, len(df1)):
  road=[localización[i]['Address']]
  postcode=[localización[i]['Postal']]
  city=[localización[i]['City']]
  department=[localización[i]['Subregion']]
  Calle.append(road)
  Codigo_Postal.append(postcode)
  Ciudad.append(city)
  Departamento.append(department)

df1['Calle'] = pd.DataFrame(Calle)
df1['Código Postal'] = pd.DataFrame(Codigo_Postal)
df1['Ciudad'] = pd.DataFrame(Ciudad)
df1['Departamento'] = pd.DataFrame(Departamento)
df1['Dirección'] = df1['Calle']+", "+df1['Código Postal']+" "+df1['Ciudad']

df1

,Nombre del Taller,Latitud,Longitud,Calle,Código Postal,Ciudad,Departamento,Dirección
0,Carrosserie M. SERVICES AUTOMOBILES,43.6163939,1.4402323,51 Boulevard des Minimes,31200,Toulouse,Haute-Garonne,"51 Boulevard des Minimes, 31200 Toulouse"
1,Garage et Carrosserie DELAMAIRE,43.6778143,1.4156883,3 Impasse Mozart,31140,Aucamville,Haute-Garonne,"3 Impasse Mozart, 31140 Aucamville"
2,Garage MECA SPORT AUTO,48.5428498,-2.2062701,5 Rue de la Croix des Tilleuls,22130,Créhen,Côtes-d'Armor,"5 Rue de la Croix des Tilleuls, 22130 Créhen"
3,Garage et Carrosserie AUTO AGM,43.6203689,6.972497,,06370,Mouans-Sartoux,Alpes-Maritimes,", 06370 Mouans-Sartoux"
4,Carrosserie M. SERVICES AUTOMOBILES,43.6054951,6.9926871,838 Avenue de Font Roubert,06250,Mougins,Alpes-Maritimes,"838 Avenue de Font Roubert, 06250 Mougins"
...,...,...,...,...,...,...,...,...
678,Garage Carrosserie GRANGIER,47.9291299,-1.941751599999975,Rue de Rennes,35330,La Chapelle-Bouëxic,Ille-et-Vilaine,"Rue de Rennes, 35330 La Chapelle-Bouëxic"
679,Garage BLANCHET Nicolas,47.425029,2.053595,33 Boulevard de la République,41300,Salbris,Loir-et-Cher,"33 Boulevard de la République, 41300 Salbris"
680,Garage AUTO OCCASION SERVICE,47.82355330000001,1.2957106999999723,7 Rue de Chateaudun,41290,Oucques La Nouvelle,Loir-et-Cher,"7 Rue de Chateaudun, 41290 Oucques La Nouvelle"
681,Carrosserie PRECICAR,48.5076567,-4.0748286,7 Boulevard Thierry d'Argenlieu,29400,Landivisiau,Finistère,"7 Boulevard Thierry d'Argenlieu, 29400 Landivi..."
682,UN SALUDO DESDE SANTANDER,43.46235,-3.80997,Plaza Ayuntamiento 1,39002,Santander,Cantabria,"Plaza Ayuntamiento 1, 39002 Santander"

Por último, procedemos a geolocalizar cada uno de los talleres en un mapa, añadiendo un popup con la dirección del mismo.

In [10]:
map1 = folium.Map(location=[47.6163939, 2.4402323], zoom_start=6)

tooltip = "Haz clic para ver el nombre del taller y la dirección"

df1.apply(lambda row:folium.Marker(location=[row["Latitud"], row["Longitud"]], popup=(row["Nombre del Taller"] + " " + row['Dirección']), tooltip=tooltip).add_to(map1), axis=1)
map1

In [25]:
# Ingresamos la dirección donde se nos ha averiado el coche. Para este ejemplo ingresaremos Aeropuerto de Pau-Pirineos aunque puedes elegir la que quieras siempre y cuando tenga talleres "cercanos"

direccion = input('Ingrese la dirección: ')

# Geolocalizamos la dirección para extraer las coordenadas GPS

averia = geolocator.geocode(direccion, timeout=None)
coche_coords = (averia.latitude, averia.longitude)

# Filtrado Espacial con (k-d Tree)

K = 5 # Elegimos el/los talleres mas cercanos en linea recta.

df1['Latitud'] = pd.to_numeric(df1['Latitud'], errors='coerce')
df1['Longitud'] = pd.to_numeric(df1['Longitud'], errors='coerce')
df1 = df1.dropna(subset=['Latitud', 'Longitud'])
coords_talleres = df1[['Latitud', 'Longitud']].values
tree = cKDTree(coords_talleres)

distancias_euclideas, indices_candidatos = tree.query(coche_coords, k=K)
candidatos_df = df1.iloc[np.atleast_1d(indices_candidatos)].copy()

# Inicializar el mapa vial

if K == 1:
    d = distancias_euclideas*100000
else:
    d = max(distancias_euclideas)*200000

G = ox.graph_from_point((coche_coords[0], coche_coords[1]), dist=d, network_type="drive")

# Mapear el coche al nodo más cercano del grafo
nodo_coche = ox.nearest_nodes(G, coche_coords[1], coche_coords[0])

# Mapear los K talleres candidatos a nodos del grafo
candidatos_df['nodo_grafo'] = ox.nearest_nodes(
    G,
    candidatos_df['Longitud'].values,
    candidatos_df['Latitud'].values
)

# Calcular la distancia real sobre la red viaria solo para los K candidatos
distancias_red = {}

for idx, row in candidatos_df.iterrows():
    nodo_taller = row['nodo_grafo']
    try:
        # Distancia en metros siguiendo las calles
        dist_metros = nx.shortest_path_length(
            G,
            source=nodo_coche,
            target=nodo_taller,
            weight='length'
        )
        distancias_red[row['Nombre del Taller']] = dist_metros
    except nx.NetworkXNoPath:
        # En caso de que el nodo esté aislado o no haya ruta posible
        distancias_red[row['Nombre del Taller']] = float('inf')

# Identificar el taller con la menor distancia en red
taller_ganador_id = min(distancias_red, key=distancias_red.get)
distancia_minima = distancias_red[taller_ganador_id]

# EXtraer coordenadas GPS del Taller más cercano
taller_ganador = candidatos_df[candidatos_df['Nombre del Taller'] == taller_ganador_id].iloc[0]
latitud_taller = taller_ganador['Latitud']
longitud_taller = taller_ganador['Longitud']

# Calcular la ruta
nodo_origen = ox.distance.nearest_nodes(G, X=averia.longitude, Y=averia.latitude)
nodo_destino = ox.distance.nearest_nodes(G, X=longitud_taller, Y=latitud_taller)

ruta = nx.shortest_path(G, source=nodo_origen, target=nodo_destino, weight="length")

# Extraer las coordenadas (lat, lon) de cada nodo de la ruta

coordenadas_ruta = []
for nodo in ruta:
    lat = G.nodes[nodo]["y"]
    lon = G.nodes[nodo]["x"]
    coordenadas_ruta.append([lat, lon])

# Crear el mapa base de Folium centrado en el inicio de la ruta

# Guardar tu clave API aquí
MI_API_KEY = "cb1_3kbu_1_961dfe3e10a17fd0bdcb4c97"

# 2. Elige el estilo de mapa que prefieras (descomenta solo uno):
# Opción A: CartoDB Positron (Fondo claro limpio)
# url_tiles =    f"https://cartocdn.com{{z}}/{{x}}/{{y}}.png?key={MI_API_KEY}"
# Opción B: CartoDB Dark Matter (Fondo oscuro elegante)
# url_tiles = f"https://basemaps.cartocdn.com/rastertiles/dark_all/{{z}}/{{x}}/{{y}}.png?key={MI_API_KEY}"

# Opción C: CartoDB Voyager (Fondo con más colores de calles)
url_tiles = f"https://basemaps.cartocdn.com/rastertiles/voyager/{{z}}/{{x}}/{{y}}.png?key={MI_API_KEY}"

# Crear el mapa pasando la URL personalizada y los créditos obligatorios
mapa = folium.Map(
    location=coordenadas_ruta[0],
    zoom_start=17,
    tiles=url_tiles,
    attr='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>',
)

# Dibujar la línea de la ruta en el mapa
folium.PolyLine(
    locations=coordenadas_ruta,
    color="blue",
    weight=5,
    opacity=0.8,
    tooltip="Ruta óptima",
).add_to(mapa)

# Añadir marcadores para el Origen y el Destino
folium.Marker(
    location=coordenadas_ruta[0],
    popup="Coche Averiado",
    icon=folium.Icon(color="green", icon="play"),
).add_to(mapa)

folium.Marker(
    location=coordenadas_ruta[-1],
    popup="Taller más cercano",
    icon=folium.Icon(color="red", icon="stop"),
).add_to(mapa)

# Mostrar mapa
mapa