# Introducción

El objetivo de este cuaderno es el de desarrollar una aplicación que nos permita calcular y graficar diversis indicadores bursátiles, minando datos a partir de un servicio de API Rest de AlphaVantage.

Para ello estaremos utilizando librerías de cálculo de indicadores para enrriquecer el Dataset con nuevas características y librerías de graficación para mostrar en gráficas los resultados.

Por último, estaremos utilizando un modelo simple de ARIMA (modelo autoregresivo) para intentar predecir el precio de cierre a futuro de la acción elegida.

# **Paso 1.**

Instalamos todas las librerías y paquetes necesarios e importamos los métodos y librerías necesarias.

Antes de comenzar no olvides activar el entorno: .\\.venv\Scripts\Activate.ps1

Luego instala con _pip install ta plotly pmdarima_

In [3]:
import numpy as np
import pandas as pd

from datetime import datetime
from datetime import timedelta

import ta

from ta import add_all_ta_features
from ta.utils import dropna
from ta.trend import ADXIndicator
from ta.trend import MACD
from ta.trend import CCIIndicator
from ta.trend import EMAIndicator
from ta.trend import SMAIndicator
from ta.volume import OnBalanceVolumeIndicator
from ta.momentum import RSIIndicator
from ta.momentum import StochasticOscillator
from ta.momentum import StochRSIIndicator

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

from pmdarima.arima import auto_arima

#**Paso 2.**

Cargamos los datos de IBM mediante la API de AlphaVantage.co.

En este caso estamos utilizando el símbolo por defecto (IBM). Si el usuario quiere analizar un símbolo diferente puede solicitar una API KEY gratuita [GET YOUR FREE API KEY TODAY](https://www.alphavantage.co/support/#api-key) para acceder a más de 200000 símbolos de distintas bolsas a nivel mundial.

In [4]:
url = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey=demo&datatype=csv"
df = pd.read_csv(url)
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  100 non-null    str
 1   open       100 non-null    float64
 2   high       100 non-null    float64
 3   low        100 non-null    float64
 4   close      100 non-null    float64
 5   volume     100 non-null    int64
dtypes: float64(4), int64(1), str(1)
memory usage: 4.8 KB

     timestamp    open      high       low   close   volume
0   2026-09-17  238.58  243.3650  237.3500  237.75  5905870
1   2026-09-16  240.50  243.3399  235.4100  237.49  6181838
2   2026-09-15  246.19  251.8150  246.1500  248.37  4518283
3   2026-09-14  249.41  251.3700  244.1201  249.09  6817275
4   2026-09-11  235.78  243.6300  235.0000  243.29  4919572
..         ...     ...       ...       ...     ...      ...
95  2026-05-01  234.55  235.9500  231.7500  232.20  3582091
96  2026-04-30  226.53  231.6000  224.9000  230.98  6283334
97  2026-04-29  230.34  231.4800  226.8200  227.10  6443724
98  2026-04-28  230.50  233.5550  228.4600  233.04  5162895
99  2026-04-27  229.95  231.3200  227.1200  228.05  8060665

[100 rows x 6 columns]

#**Paso 3.**

Manipulamos los datos para parsear correctamente la variable temporal y mostramos las estadísticas descriptivas de las variables que integran el DataFrame

In [5]:
Date = []

for index, row in df.iterrows():
  dia = datetime.strptime(row['timestamp'], '%Y-%m-%d')
  Date.append(dia)
df['date'] = pd.DataFrame(Date)
df.info()

dfw = pd.DataFrame()
dfw = df.drop(columns=['timestamp'])
dfw = dfw.reindex(columns=['date', 'open', 'high', 'low', 'close', 'volume'])
dfw.info()
dfw = dfw.iloc[::-1]
dfw.reset_index(drop=True, inplace=True)


last_date = dfw['date'].values[len(dfw)-1]
next_date = last_date + 86400000000000 # Este número es un día llevado a nanosegundos. Si se elige otro espaciado temporal entre las observaciones habría que ajustarlo

new_row = pd.DataFrame({ 'date': [next_date]})
dfw = pd.concat([dfw, new_row])
dfw.reset_index(drop=True, inplace=True)
dfw.describe()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  100 non-null    str
 1   open       100 non-null    float64
 2   high       100 non-null    float64
 3   low        100 non-null    float64
 4   close      100 non-null    float64
 5   volume     100 non-null    int64
 6   date       100 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(1), str(1)
memory usage: 5.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    100 non-null    datetime64[us]
 1   open    100 non-null    float64
 2   high    100 non-null    float64
 3   low     100 non-null    float64
 4   close   100 non-null    float64
 5   volume  100 non-null    int64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 4.8 KB

C:\Users\jorge.crespo.UNEATPDIPAS\AppData\Local\Temp\ipykernel_8404\3039918909.py:18: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  next_date = last_date + 86400000000000 # Este número es un día llevado a nanosegundos. Si se elige otro espaciado temporal entre las observaciones habría que ajustarlo

,date,open,high,low,close,volume
count,101,100.00000,100.000000,100.000000,100.000000,1.000000e+02
mean,2026-07-17 23:02:58.217821,245.61153,250.205765,241.631762,246.351400,9.032804e+06
min,2026-04-27 00:00:00,202.64000,207.550000,199.190000,205.770000,3.023636e+06
25%,2026-06-02 00:00:00,228.57750,230.992500,224.860000,227.925000,5.128232e+06
50%,2026-07-09 00:00:00,234.46500,238.667500,232.005000,235.635000,6.570695e+06
75%,2026-08-13 00:00:00,263.12500,268.875000,257.320000,264.400000,9.352911e+06
max,2029-06-13 00:00:00,322.55000,332.460000,310.109000,329.230000,6.744087e+07
std,NaN,27.88575,29.125129,26.480452,28.067403,8.134813e+06

In [6]:
dfw

          date    open      high       low   close     volume
0   2026-04-27  229.95  231.3200  227.1200  228.05  8060665.0
1   2026-04-28  230.50  233.5550  228.4600  233.04  5162895.0
2   2026-04-29  230.34  231.4800  226.8200  227.10  6443724.0
3   2026-04-30  226.53  231.6000  224.9000  230.98  6283334.0
4   2026-05-01  234.55  235.9500  231.7500  232.20  3582091.0
..         ...     ...       ...       ...     ...        ...
96  2026-09-14  249.41  251.3700  244.1201  249.09  6817275.0
97  2026-09-15  246.19  251.8150  246.1500  248.37  4518283.0
98  2026-09-16  240.50  243.3399  235.4100  237.49  6181838.0
99  2026-09-17  238.58  243.3650  237.3500  237.75  5905870.0
100 2029-06-13     NaN       NaN       NaN     NaN        NaN

[101 rows x 6 columns]

#**Paso 4.**

Dibujamos los gráficos de series temporales para el símbolo seleccionado (IBM)

In [7]:
fig = go.Figure(data=[go.Ohlc(x=df['date'],
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close'])])
fig.update_layout(
    title='Gráfico Open, High, Low, Close',
    yaxis_title='IBM',
    xaxis_title='Fecha')

fig1 = px.line(df, x="date", y="close")
fig1.update_layout(
    title='Precio de Cierre',
    yaxis_title='IBM',
    xaxis_title='Fecha')

fig.show()
fig1.show()

#**Paso 5.**

Utilizaremos la librería [ta](https://technical-analysis-library-in-python.readthedocs.io/en/latest/) para calcular los indicadores técnicos para poder realizar análisis técnico del precio de la acción de IBM.

In [8]:
dfw['OPEN-1'] = dfw["open"].shift(1)
dfw['HIGH-1'] = dfw["high"].shift(1)
dfw['LOW-1'] = dfw["low"].shift(1)
dfw['CLOSE-1'] = dfw["close"].shift(1)
dfw['VOLUME-1'] = dfw["volume"].shift(1)

np.seterr(divide='ignore', invalid='ignore')

indicator_adx = ADXIndicator(close=dfw["CLOSE-1"], high=dfw["HIGH-1"], low=dfw["LOW-1"], window=14, fillna=True)
dfw['ADX14'] = indicator_adx.adx()

indicator_ema = EMAIndicator(close=dfw["CLOSE-1"], window=14)
dfw['EMA14'] = indicator_ema.ema_indicator()

indicator_sma7 = SMAIndicator(close=dfw["CLOSE-1"], window=7)
dfw['SMA7'] = indicator_sma7.sma_indicator()

indicator_sma26 = SMAIndicator(close=dfw["CLOSE-1"], window=26)
dfw['SMA26'] = indicator_sma26.sma_indicator()

indicator_sma42 = SMAIndicator(close=dfw["CLOSE-1"], window=42)
dfw['SMA42'] = indicator_sma42.sma_indicator()

indicator_macd = MACD(close=dfw["CLOSE-1"], window_slow=26, window_fast= 12, window_sign=9)
dfw['MACD'] = indicator_macd.macd()
dfw['MACD_SIGNAL'] =indicator_macd.macd_signal()

indicator_rsi = RSIIndicator(close=dfw["CLOSE-1"], window=14)
dfw['RSI'] =indicator_rsi.rsi()

indicator_cci = CCIIndicator(high=dfw["HIGH-1"], low=dfw["LOW-1"], close=dfw["CLOSE-1"], window=20, constant=0.15)
dfw['CCI'] =indicator_cci.cci()

indicator_RSIstochastic = StochRSIIndicator(close=dfw["CLOSE-1"], window=15, smooth1=3, smooth2=3)
dfw['RSIK'] =indicator_RSIstochastic.stochrsi_k()
dfw['RSID'] =indicator_RSIstochastic.stochrsi_d()

indicator_stochastic = StochasticOscillator(close=dfw["CLOSE-1"], high=dfw["HIGH-1"], low=dfw["LOW-1"], window=15, smooth_window=3)
dfw['K'] =indicator_stochastic.stoch()
dfw['D'] =indicator_stochastic.stoch_signal()
dfw['DIFF_K-D'] =indicator_stochastic.stoch()-indicator_stochastic.stoch_signal()

indicator_obv = OnBalanceVolumeIndicator(close=dfw["CLOSE-1"], volume=dfw["VOLUME-1"])
dfw['OBV'] =indicator_obv.on_balance_volume()

dfw['CLOSEDIFF'] =(dfw["CLOSE-1"]-dfw["OPEN-1"])/dfw["OPEN-1"]

ibm_TI_df = dfw
ibm_TI_df.info()

ibm_TI_df_topredict = ibm_TI_df[-1:]
ibm_TI_df = ibm_TI_df[:-1]
ibm_TI_df = ibm_TI_df.dropna()
ibm_TI_df.reset_index(drop=True, inplace=True)
ibm_TI_df.info()
ibm_TI_df

<class 'pandas.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         101 non-null    datetime64[us]
 1   open         100 non-null    float64
 2   high         100 non-null    float64
 3   low          100 non-null    float64
 4   close        100 non-null    float64
 5   volume       100 non-null    float64
 6   OPEN-1       100 non-null    float64
 7   HIGH-1       100 non-null    float64
 8   LOW-1        100 non-null    float64
 9   CLOSE-1      100 non-null    float64
 10  VOLUME-1     100 non-null    float64
 11  ADX14        101 non-null    float64
 12  EMA14        87 non-null     float64
 13  SMA7         94 non-null     float64
 14  SMA26        75 non-null     float64
 15  SMA42        59 non-null     float64
 16  MACD         75 non-null     float64
 17  MACD_SIGNAL  67 non-null     float64
 18  RSI          88 non-null     float64
 19  CCI          81 non-null     float64
 20  RSIK         71 non-null     float64
 21  RSID         69 non-null     float64
 22  K            86 non-null     float64
 23  D            84 non-null     float64
 24  DIFF_K-D     84 non-null     float64
 25  OBV          100 non-null    float64
 26  CLOSEDIFF    100 non-null    float64
dtypes: datetime64[us](1), float64(26)
memory usage: 21.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         58 non-null     datetime64[us]
 1   open         58 non-null     float64
 2   high         58 non-null     float64
 3   low          58 non-null     float64
 4   close        58 non-null     float64
 5   volume       58 non-null     float64
 6   OPEN-1       58 non-null     float64
 7   HIGH-1       58 non-null     float64
 8   LOW-1        58 non-null     float64
 9   CLOSE-1      58 non-null     float64
 10  VOLUME-1     58 non-null     float64
 11  ADX14        58 non-null     float64
 12  EMA14        58 non-null     float64
 13  SMA7         58 non-null     float64
 14  SMA26        58 non-null     float64
 15  SMA42        58 non-null     float64
 16  MACD         58 non-null     float64
 17  MACD_SIGNAL  58 non-null     float64
 18  RSI          58 non-null     float64
 19  CCI          58 non-null     float64
 20  RSIK         58 non-null     float64
 21  RSID         58 non-null     float64
 22  K            58 non-null     float64
 23  D            58 non-null     float64
 24  DIFF_K-D     58 non-null     float64
 25  OBV          58 non-null     float64
 26  CLOSEDIFF    58 non-null     float64
dtypes: datetime64[us](1), float64(26)
memory usage: 12.4 KB

,date,open,high,low,close,volume,OPEN-1,HIGH-1,LOW-1,CLOSE-1,...,MACD_SIGNAL,RSI,CCI,RSIK,RSID,K,D,DIFF_K-D,OBV,CLOSEDIFF
0,2026-06-26,258.940,273.1350,258.2800,271.63,9719927.0,267.670,268.7559,256.0000,258.27,...,5.993491,47.318493,-6.818980,0.201035,0.141947,21.854404,23.880182,-2.025779,61212857.0,-0.035118
1,2026-06-29,274.300,278.1500,269.0600,278.00,6464204.0,258.940,273.1350,258.2800,271.63,...,5.188542,54.223766,-4.330194,0.353050,0.235795,47.679973,31.791228,15.888744,70932784.0,0.049007
2,2026-06-30,273.210,282.5694,271.1200,281.21,7458360.0,274.300,278.1500,269.0600,278.00,...,4.707584,57.110404,-1.154521,0.565028,0.373038,73.302008,47.612128,25.689880,77396988.0,0.013489
3,2026-07-01,279.660,294.4900,278.9600,286.25,6905811.0,273.210,282.5694,271.1200,281.21,...,4.495395,58.529594,1.216458,0.838169,0.585416,94.036582,71.672854,22.363728,84855348.0,0.029282
4,2026-07-02,283.140,290.9300,282.2800,289.52,5950158.0,279.660,294.4900,278.9600,286.25,...,4.532953,60.726918,7.475903,0.960440,0.787879,83.782720,83.707103,0.075617,91761159.0,0.023564
5,2026-07-06,288.345,300.8199,287.6500,299.52,7181525.0,283.140,290.9300,282.2800,289.52,...,4.766918,62.128972,9.712669,1.000000,0.932869,90.218461,89.345921,0.872540,97711317.0,0.022533
6,2026-07-07,305.660,311.8000,300.4901,306.13,8618569.0,288.345,300.8199,287.6500,299.52,...,5.260402,66.113142,16.195531,1.000000,0.986813,97.725057,90.575413,7.149645,104892842.0,0.038756
7,2026-07-08,300.770,303.8200,295.5900,302.05,7416749.0,305.660,311.8000,300.4901,306.13,...,5.984146,68.474081,20.754856,1.000000,1.000000,91.676453,93.206657,-1.530204,113511411.0,0.001538
8,2026-07-09,285.835,297.2838,284.4381,295.30,10841979.0,300.770,303.8200,295.5900,302.05,...,6.735541,65.443250,15.293121,0.962274,0.987425,85.687023,91.696178,-6.009155,106094662.0,0.004256
9,2026-07-10,297.260,298.7700,287.5000,287.56,3640089.0,285.835,297.2838,284.4381,295.30,...,7.341834,60.659560,9.433843,0.864833,0.942369,75.778039,84.380505,-8.602466,95252683.0,0.033114
10,2026-07-13,290.500,297.5000,289.1000,290.23,5024243.0,297.260,298.7700,287.5000,287.56,...,7.685175,55.637439,7.801096,0.704346,0.843818,64.415737,75.293600,-10.877863,91612594.0,-0.032631
11,2026-07-14,226.365,229.9200,213.2200,217.07,67440873.0,290.500,297.5000,289.1000,290.23,...,7.870787,56.961181,7.382569,0.587319,0.718833,68.274746,69.489507,-1.214761,96636837.0,-0.000929
12,2026-07-15,220.965,223.8130,211.0300,211.20,29590356.0,226.365,229.9200,213.2200,217.07,...,6.762644,30.290301,-21.820690,0.351427,0.547697,3.905457,45.531980,-41.626523,29195964.0,-0.041062
13,2026-07-16,208.820,219.9500,204.4400,219.05,22533271.0,220.965,223.8130,211.0300,211.20,...,4.792624,29.112461,-19.448284,0.178581,0.372442,0.168701,24.116302,-23.947601,-394392.0,-0.044193
14,2026-07-17,215.620,217.1699,210.2200,212.67,13150177.0,208.820,219.9500,204.4400,219.05,...,2.499987,32.871739,-16.353943,0.031352,0.187120,13.608420,5.894193,7.714227,22138879.0,0.048990
15,2026-07-20,210.070,216.2762,208.8200,213.00,9585016.0,215.620,217.1699,210.2200,212.67,...,0.017838,31.413635,-14.175507,0.050049,0.086661,7.665797,7.147640,0.518158,8988702.0,-0.013681
16,2026-07-21,210.720,214.9700,209.1800,210.50,11954411.0,210.070,216.2762,208.8200,213.00,...,-2.447753,31.582683,-12.851409,0.070149,0.050517,7.973174,9.749131,-1.775956,18573718.0,0.013948
17,2026-07-22,207.680,212.3417,204.7300,205.77,14606736.0,210.720,214.9700,209.1800,210.50,...,-4.808021,30.960117,-11.726900,0.053532,0.057910,5.644560,7.094511,-1.449950,6619307.0,-0.001044
18,2026-07-23,202.640,207.5500,199.1900,206.65,15306010.0,207.680,212.3417,204.7300,205.77,...,-7.043052,29.764636,-10.761304,0.039286,0.054322,1.238823,4.952186,-3.713363,-7987429.0,-0.009197
19,2026-07-24,209.280,216.1000,206.8000,214.19,10578780.0,202.640,207.5500,199.1900,206.65,...,-9.052330,30.303843,-9.836267,0.028059,0.040292,6.624634,4.502672,2.121961,7318581.0,0.019789
20,2026-07-27,217.750,219.6300,215.2900,216.28,8369433.0,209.280,216.1000,206.8000,214.19,...,-10.673852,34.914441,-7.420591,0.059985,0.042444,13.320309,7.061255,6.259054,17897361.0,0.023461
21,2026-07-28,219.730,228.9800,215.1101,227.55,13262958.0,217.750,219.6300,215.2900,216.28,...,-11.909662,36.174817,-5.951807,0.112533,0.066859,15.176272,11.707072,3.469200,26266794.0,-0.006751
22,2026-07-29,227.700,230.9700,223.9500,226.44,8806699.0,219.730,228.9800,215.1101,227.55,...,-12.631980,42.626715,-4.346632,0.222664,0.131727,27.105037,18.533873,8.571164,39529752.0,0.035589
23,2026-07-30,222.000,224.8600,220.2000,221.74,9675157.0,227.700,230.9700,223.9500,226.44,...,-12.983505,42.174516,-3.427065,0.307830,0.214342,27.364933,23.215414,4.149519,30723053.0,-0.005534
24,2026-07-31,221.150,224.7600,216.5850,223.65,9093613.0,222.000,224.8600,220.2000,221.74,...,-13.129590,40.228524,-3.893565,0.377198,0.302564,22.645109,25.705026,-3.059917,21047896.0,-0.001171
25,2026-08-03,228.330,228.5500,224.8700,226.31,7974681.0,221.150,224.7600,216.5850,223.65,...,-13.078854,41.411627,-3.642957,0.398118,0.361049,24.880480,24.963507,-0.083027,30141509.0,0.011305
26,2026-08-04,224.760,235.3100,223.3000,235.15,7537896.0,228.330,228.5500,224.8700,226.31,...,-12.835165,43.100776,-2.244442,0.599623,0.458313,85.336690,44.287426,41.049263,38116190.0,-0.008847
27,2026-08-05,236.100,238.9627,233.4600,235.92,5726854.0,224.760,235.3100,223.3000,235.15,...,-12.313021,48.422720,-0.450562,0.806590,0.601444,99.557032,69.924734,29.632298,45654086.0,0.046227
28,2026-08-06,229.610,234.4700,228.4400,233.43,4250062.0,236.100,238.9627,233.4600,235.92,...,-11.603370,48.871312,2.198775,1.000000,0.802071,92.349778,92.414500,-0.064722,51380940.0,-0.000762
29,2026-08-07,235.380,237.3150,232.7200,237.28,4763304.0,229.610,234.4700,228.4400,233.43,...,-10.826674,47.434561,2.414498,0.975333,0.927308,86.089202,92.665337,-6.576135,47130878.0,0.016637
30,2026-08-10,235.000,240.7350,234.1300,236.31,7348858.0,235.380,237.3150,232.7200,237.28,...,-9.962570,49.887677,6.946658,0.975333,0.983555,95.769209,91.402729,4.366479,51894182.0,0.008072
31,2026-08-11,236.310,241.8000,235.4400,238.42,4468987.0,235.000,240.7350,234.1300,236.31,...,-9.081748,49.263882,12.876887,0.965236,0.971967,89.348899,90.402436,-1.053538,44545324.0,0.005574
32,2026-08-12,236.950,237.4600,231.6800,235.98,5696182.0,236.310,241.8000,235.4400,238.42,...,-8.182258,50.707735,12.206062,0.989903,0.976824,92.067590,92.395232,-0.327643,49014311.0,0.008929
33,2026-08-13,238.920,239.7100,233.6100,237.14,5395192.0,236.950,237.4600,231.6800,235.98,...,-7.338501,48.972145,8.596764,0.962356,0.972498,86.341234,89.252574,-2.911340,43318129.0,-0.004094
34,2026-08-14,238.370,239.1500,233.7300,234.32,4523467.0,238.920,239.7100,233.6100,237.14,...,-6.538673,49.850942,8.902664,0.955185,0.969148,86.685714,88.364846,-1.679132,48713321.0,-0.007450
35,2026-08-17,231.590,233.6500,227.4000,228.85,7564317.0,238.370,239.1500,233.7300,234.32,...,-5.838396,47.700253,7.408822,0.888667,0.935403,71.974417,81.667122,-9.692705,44189854.0,-0.016990
36,2026-08-18,229.730,234.4499,229.4150,232.67,4650116.0,231.590,233.6500,227.4000,228.85,...,-5.311189,43.756834,2.881093,0.701713,0.848522,51.479773,70.046635,-18.566862,36625537.0,-0.011831
37,2026-08-19,232.260,238.6150,230.5100,237.16,5342567.0,229.730,234.4499,229.4150,232.67,...,-4.847046,47.049039,4.082209,0.606962,0.732447,63.791394,62.415195,1.376199,41275653.0,0.012798
38,2026-08-20,236.000,237.5000,233.0300,233.69,4986890.0,232.260,238.6150,230.5100,237.16,...,-4.364077,50.701757,6.247169,0.673480,0.660718,81.598255,65.623141,15.975114,46618220.0,0.021097
39,2026-08-21,233.710,238.7200,233.1200,235.68,3888743.0,236.000,237.5000,233.0300,233.69,...,-3.940043,47.948869,5.190858,0.792850,0.691097,67.836605,71.075418,-3.238813,41631330.0,-0.009788
40,2026-08-24,234.370,234.4900,230.4700,231.04,4085030.0,233.710,238.7200,233.1200,235.68,...,-3.534446,49.637675,6.073676,0.860956,0.775762,66.918919,72.117926,-5.199007,45520073.0,0.008429
41,2026-08-25,230.000,234.4350,229.5100,234.19,3023636.0,234.370,234.4900,230.4700,231.04,...,-3.227641,45.898327,-0.009619,0.633287,0.762365,41.837838,58.864454,-17.026616,41435043.0,-0.014208
42,2026-08-26,230.700,234.2300,228.9600,229.87,4631964.0,230.000,234.4350,229.5100,234.19,...,-2.941227,48.722483,0.477344,0.636303,0.710182,47.152778,51.969845,-4.817067,44458679.0,0.018217
43,2026-08-27,232.800,240.8065,231.4500,238.79,5505922.0,230.700,234.2300,228.9600,229.87,...,-2.744827,45.235012,-3.113427,0.421413,0.563668,17.152778,35.381131,-18.228353,39826715.0,-0.003598
44,2026-08-28,238.300,239.0800,235.0900,235.59,3945403.0,232.800,240.8065,231.4500,238.79,...,-2.466573,52.754786,7.834765,0.649082,0.568933,79.097222,47.800926,31.296296,45332637.0,0.025730
45,2026-08-31,232.730,235.9379,232.1800,233.87,6101445.0,238.300,239.0800,235.0900,235.59,...,-2.197032,50.097213,6.512471,0.644442,0.571646,56.875000,51.041667,5.833333,41387234.0,-0.011372
46,2026-09-01,231.000,233.0900,229.9000,231.40,3240341.0,232.730,235.9379,232.1800,233.87,...,-1.969517,48.677773,-1.610862,0.754723,0.682749,44.930556,60.300926,-15.370370,35285789.0,0.004898
47,2026-09-02,230.545,232.8800,229.1000,231.70,4654576.0,231.000,233.0900,229.9000,231.40,...,-1.815188,46.634330,-9.846522,0.531603,0.643589,29.836273,43.880610,-14.044336,32045448.0,0.001732
48,2026-09-03,234.380,238.2900,232.8150,234.71,4375426.0,230.545,232.8800,229.1000,231.70,...,-1.705898,46.925754,-9.331931,0.415873,0.567400,32.073994,35.613608,-3.539614,36700024.0,0.005010
49,2026-09-04,233.330,236.1700,231.6800,234.89,3722860.0,234.380,238.2900,232.8150,234.71,...,-1.578655,49.882936,2.725483,0.459870,0.469115,54.525790,38.812019,15.713771,41075450.0,0.001408
50,2026-09-08,232.950,233.4000,230.2000,232.09,4787646.0,233.330,236.1700,231.6800,234.89,...,-1.440360,50.062127,-0.322441,0.585013,0.486919,55.868422,47.489402,8.379020,44798310.0,0.006686
51,2026-09-09,232.650,241.5000,230.3600,239.94,6404717.0,232.950,233.4000,230.2000,232.09,...,-1.343777,47.233044,-7.184787,0.556393,0.533759,26.421306,45.605173,-19.183867,40010664.0,-0.003692
52,2026-09-10,238.180,242.3100,231.8300,234.02,5820269.0,232.650,241.5000,230.3600,239.94,...,-1.150096,54.923965,10.955322,0.660916,0.600774,87.559809,56.616512,30.943296,46415381.0,0.031335
53,2026-09-11,235.780,243.6300,235.0000,243.29,4919572.0,238.180,242.3100,231.8300,234.02,...,-0.997539,49.110592,6.536042,0.562414,0.593241,37.902622,50.627912,-12.725290,40595112.0,-0.017466
54,2026-09-14,249.410,251.3700,244.1201,249.09,6817275.0,235.780,243.6300,235.0000,243.29,...,-0.728583,56.818052,19.378440,0.803520,0.675617,97.682345,74.381592,23.300753,45514684.0,0.031852
55,2026-09-15,246.190,251.8150,246.1500,248.37,4518283.0,249.410,251.3700,244.1201,249.09,...,-0.306573,60.816738,31.332657,0.803520,0.723151,89.825971,75.136979,14.688991,52331959.0,-0.001283
56,2026-09-16,240.500,243.3399,235.4100,237.49,6181838.0,246.190,251.8150,246.1500,248.37,...,0.178457,60.073062,25.579603,0.984548,0.863863,84.926712,90.811676,-5.884964,47813676.0,0.008855
57,2026-09-17,238.580,243.3650,237.3500,237.75,5905870.0,240.500,243.3399,235.4100,237.49,...,0.503569,50.102848,5.059492,0.760015,0.849361,37.322249,70.691644,-33.369395,41631838.0,-0.012516

#**Paso 6.**

Creamos un gráfico con algunos de los indicadores técnicos calculados.

In [9]:
fig2 = make_subplots(rows=3, cols=1)

fig2.append_trace(go.Candlestick(x=ibm_TI_df['date'],
                open=ibm_TI_df['open'],
                high=ibm_TI_df['high'],
                low=ibm_TI_df['low'],
                close=ibm_TI_df['close'], name='Gráfico de Velas'), row=1, col=1)
fig2.append_trace(go.Scatter(x=ibm_TI_df['date'], y=ibm_TI_df['close'], mode='lines', name='Cierre', line=dict(color='firebrick', width=3, dash='dot')), row=1, col=1)
fig2.append_trace(go.Scatter(x=ibm_TI_df['date'], y=ibm_TI_df['SMA7'], mode='lines', name='SMA7', line=dict(color='royalblue', width=3, dash='dot')), row=1, col=1)

fig2.append_trace(go.Scatter(x=ibm_TI_df['date'], y=ibm_TI_df['MACD'], mode='lines', name='MACD'), row=2, col=1)
fig2.append_trace(go.Scatter(x=ibm_TI_df['date'], y=ibm_TI_df['MACD_SIGNAL'], mode='lines', name='Señal MACD'), row=2, col=1)
fig2.add_hline(y=0, row=2, col=1, line=dict(color='gray', dash='dot'))

fig2.append_trace(go.Scatter(x=ibm_TI_df['date'], y=ibm_TI_df['RSI'], mode='lines', name='RSI'), row=3, col=1)
fig2.add_hline(y=80, row=3, col=1, line=dict(color='red', dash='dash'))
fig2.add_hline(y=20, row=3, col=1, line=dict(color='blue', dash='dash'))
fig2.update_layout(yaxis3 = dict(range=[0, 100]))

fig2.update_layout(
    height=800, width=1400,
    yaxis1_title='Velas y Media Móvil',
    yaxis2_title='MACD y Señal MACD',
    yaxis3_title='RSI',
    xaxis3_title='Fecha',
    xaxis1_rangeslider_visible=False)

fig2.show()

#**Paso 7.**

Ahora intentaremos hacer una predicción del precio futuro (un día por delante) del cierre de IBM. Utilizaremos dos modelos básicos:
* Regresión lineal múltiple sobre datos defasados
* Autoregresión (AutoARIMA)

In [10]:
TRAIN = ibm_TI_df.iloc[0:int(len(ibm_TI_df)//(1/0.90))]
TEST = ibm_TI_df.iloc[int(len(ibm_TI_df)//(1/0.90))+1:-1]

x_train =TRAIN.drop(columns=['open', 'close', 'high', 'low', 'volume', 'date'])
y_train = TRAIN['close']
x_test =TEST.drop(columns=['open', 'close', 'high', 'low', 'volume', 'date'])
y_test = TEST['close']

reg = LinearRegression().fit(x_train, y_train)
y_hat = reg.predict(x_test)
R2 = r2_score(y_test, y_hat)
if R2 < 0:
  print("El Modelo no es capaz de ajustar bien los datos, R^2 =",R2, "Una predicción arbitraria sería mejor")

x_predict = ibm_TI_df_topredict.drop(columns=['open', 'close', 'high', 'low', 'volume', 'date'])
prediction = reg.predict(x_predict).astype(float)

print("La predicción para el día ", next_date, "es ", prediction)

El Modelo no es capaz de ajustar bien los datos, R^2 = -2.565534252896955 Una predicción arbitraria sería mejor
La predicción para el día  2029-06-13T00:00:00.000000 es  [241.55172768]

In [11]:
X_train =ibm_TI_df['close']

model = auto_arima(X_train, start_p=1, start_q=1,
                      test='adf',
                      max_p=5, max_q=5,
                      m=1,
                      d=1,
                      seasonal=True,
                      start_P=0,
                      D=None,
                      trace=True,
                      error_action='ignore',
                      suppress_warnings=True,
                      stepwise=True)

Performing stepwise search to minimize aic
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=442.024, Time=0.08 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=438.169, Time=0.01 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=440.136, Time=0.01 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=440.136, Time=0.02 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=436.338, Time=0.01 sec

Best model:  ARIMA(0,1,0)(0,0,0)[0]
Total fit time: 0.131 seconds

In [12]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   58
Model:               SARIMAX(0, 1, 0)   Log Likelihood                -217.169
Date:                Fri, 18 Sep 2026   AIC                            436.338
Time:                        09:51:14   BIC                            438.381
Sample:                             0   HQIC                           437.132
                                 - 58
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
sigma2       119.3540      5.391     22.138      0.000     108.787     129.921
===================================================================================
Ljung-Box (L1) (Q):                   0.04   Jarque-Bera (JB):              2598.45
Prob(Q):                              0.85   Prob(JB):                         0.00
Heteroskedasticity (H):               0.09   Skew:                            -5.08
Prob(H) (two-sided):                  0.00   Kurtosis:                        34.48
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [13]:
prediction, confint = model.predict(n_periods=1, return_conf_int=True)

print(prediction)
print(confint)

58    237.75
dtype: float64
[[216.33754339 259.16245661]]